import Environment from '../../../../common-core/src/environment/environment';
import { RapiMaterial } from '../../../../typings/rapi-types';
import BakedShadowEnvironment from '../../../../common-core/src/environment/baked-shadow-environment';
export default class FloorEnvironment extends BakedShadowEnvironment {
    private _rapiAccess;
    private _dataSyncer;
    private _environmentLoader;
    private _bakedShadowPlane;
    private _textureLoader;
    private _longestSide;
    private _width;
    private _height;
    private _cameraDistance;
    private _repeatable;
    private _floorMaterial;
    private _floorTexture;
    private _fog;
    private _floorPromise;
    constructor(scene: THREE.Scene, oldEnvironment: Environment, fog?: boolean);
    needsBounds(): boolean;
    needsCamera(): boolean;
    needsRotation(): boolean;
    updateBounds(bounds: THREE.Vector3): boolean;
    updateCamera(camera: THREE.PerspectiveCamera): void;
    private _update;
    private _updateFog;
    private _updateFloor;
    addToScene(): void;
    removeFromScene(): void;
    setFloorMaterial(url: string, width: number, height: number, repeatable: boolean): Promise<void>;
    changeFloorMaterial(rapiMaterial: RapiMaterial, maxAnisotropy?: number): Promise<void>;
    showGUI(): void;
    private _addGUI;
}
