import Component from '@glimmer/component';
import UiCore from '../../../services/ui-core';
import CoreEventHandler from '../../../services/core-event-handler';
import EventHandler from '../../../services/event-handler';
import I18n from '../../../services/i18n';
export default class SideBar extends Component {
    protected _uiCore: UiCore;
    protected _coreEventHandler: CoreEventHandler;
    protected _eventHandler: EventHandler;
    protected _i18n: I18n;
    private _embed;
    state: {
        isShowAddons: boolean;
        isShowSidebar: boolean;
        isSidebarAlwaysHidden: boolean;
        isParameterDetails: boolean;
        isDetailsOpen: boolean;
        isMultiselect: boolean;
        isDragging: boolean;
        isSomethingSelected: boolean;
        isRoot: boolean;
        showAddonButton: boolean;
        hasChildren: boolean;
        detailParameter: any;
        addons: any[];
        parameters: any[];
        defaultChild: any;
        typeChangeTag: any;
        lastGroup: any;
    };
    readonly hideAddButton: boolean;
    readonly isSelectionCancelable: boolean;
    readonly parameters: any[];
    private _closeAddonsOnNext;
    constructor(object: object);
    private _onUpdateParameters;
    private _onLoadConfiguration;
    private _reset;
    private _onUpdatePossibleChildren;
    private _onSelectionChange;
    private _onSelectionCancel;
    private _changeSelection;
    private _onRemovePreviews;
    toggleAddons(): void;
    private _handleDefaultChildWhileOpenAddons;
    private _onOpenAddons;
    private _onClickOutside;
    private _onChangeTypeChangeTag;
    private _onRemoveTypeChangeTag;
    onAddonClicked(): void;
    toggleParameterDetails(parameter?: any): void;
    onShowDetailsInGroup(parameter: any): void;
    toggleSidebar(): void;
    onShowDetails(detailParameter: any): void;
    previewDockingsDone(child: UiPossibleChild): void;
    onAddonDragStarted(child: UiPossibleChild, dragEvent: DragEvent): void;
    onAddonDragEnded(): void;
    cancelSelection(): void;
    loadAddonImages(): void;
    onCustomize(): void;
}
