import { ScenePlugin } from '../webgl/plugin-system';
export default class DimensioningHelper implements ScenePlugin {
    _creator_: string;
    private _unitFormatter;
    private _scene;
    private _uiScene;
    private _cameraPosition;
    private _lineBounds;
    private _textUpdated;
    private _font;
    private _onChange;
    private _topDimensions;
    private _initialized;
    private _dimensions;
    private _lineMaterial;
    private _planeMaterial;
    private _widthLine;
    private _heightLine;
    private _depthLine;
    private _widthText;
    private _heightText;
    private _depthText;
    private _enabled;
    private _dimensionsVisible;
    constructor(creator: string);
    private _loaded;
    private _performUpdate;
    private _updateWidth;
    private _updateHeight;
    private _updateDepth;
    updateBounds(boxForMeasurements: THREE.Box3): void;
    update(force?: boolean): void;
    addToScene(scene: THREE.Scene, uiScene: THREE.Scene): void;
    removeFromScene(scene: THREE.Scene, uiScene: THREE.Scene): void;
    private _getWidthEdge;
    private _getDepthEdge;
    private _getHeightEdge;
    onDimensionsVisibilityChanged(handler: (visible: boolean) => void): void;
    enableTopDimensions(): void;
    disableTopDimensions(): void;
    enableDimensions(): void;
    disableDimensions(): void;
    private _visibilityChangedCallback;
    _clear(): void;
    getBoundingBox(): THREE.Box3;
    private setVisibility;
    moveCameraStart(position: THREE.Vector3): void;
    moveCameraEnd(position: THREE.Vector3): void;
    clearScene(scene: THREE.Scene): void;
    setScene(scene: THREE.Scene): void;
    setUiScene(uiScene: THREE.Scene): void;
    needsUiScene(): boolean;
    isInitialized(): Promise<void>;
}
