export declare const FeatureDetection: {
    isOldBrowser(): boolean;
    hasStaticSupport(): any;
    hasEs6ModuleSupport(): boolean;
    _hasEs6Support(): boolean;
    _hasNativeCSSProperties(): boolean;
    _class(): any;
    _arrowFunction(): any;
    _let(): any;
    _const(): any;
    _collections(): boolean;
    _templateStrings(): any;
    _symbols(): boolean;
    _destructuring(): any;
    _asyncAwait(): any;
    _spread(): any;
    _defaultParamValues(): any;
    _supportsStaticImport(): boolean;
    _supportsDynamicImport(): boolean;
    _evaluates(statement: any): any;
};
