import Component from '@glimmer/component';
import LocalStorage from '../../../services/local-storage';
export default class RoomleConfigurator extends Component {
    private _embed;
    private _coreEventHandler;
    private _eventHandler;
    private _loadingScreen;
    protected _localStorage: LocalStorage;
    private _i18n;
    private _uiCore;
    private _gaInterface;
    private _globalState;
    private _oneDockCompleted;
    private _isSaving;
    private _initSentToIframe;
    partList: {
        data: KernelPart[];
    };
    state: {
        price: any;
        initTag: any;
        hasTag: boolean;
        isInitialized: boolean;
        isActionbarIntersected: boolean;
        isShareOpen: boolean;
        isSidebarIntersected: boolean;
        isBottomIntersected: boolean;
        isConfigurationLoaded: boolean;
        isOfflineError: boolean;
        isTagOpen: boolean;
        isInfoOpen: boolean;
        isError: boolean;
        isInitTag: boolean;
        isBubbleOpen: boolean;
        isPrint: boolean;
        tagToShow: RapiTag | PlaceholderTag;
        initialMultiselect: boolean;
        bubbleText: string;
        hideBubble: boolean;
        numSavedConfigurations: number;
        currentPerspectiveImage: any;
        currentLabel: string;
        currentDimensions: KernelBoundsFormatted;
        isFirefoxOnAndroid: boolean;
    };
    readonly initLabel: any;
    readonly isNotInitTag: boolean;
    readonly isCloseable: boolean;
    didInsertElement(): void;
    constructor(options: object);
    private _handleSkin;
    onConfigurationLoaded(partListData?: any): void;
    onIsInitialized(): void;
    private _kernelPartListToArray;
    private _onLoadConfiguration;
    private _onConfigurationLabelChange;
    private _onConfigurationReady;
    private _onPartListUpdate;
    private _onComponentLoadError;
    private _onConfigurationLoadingError;
    private _onPriceUpdate;
    private _onConfigurationHasChildren;
    private _onTrackTiming;
    onCloseToast(): void;
    toggleFullscreen(isFullscreen: boolean): void;
    private _offlineError;
    onRemove(id: RapiId): void;
    onCloseOverlayAfterTag(ensuresInitialization: boolean): void;
    onCloseOverlay(): void;
    onOpenInitTag(): void;
    onOpenLoad(tag: PlaceholderTag): void;
    onOpenInfo(): void;
    onOpenShare(): void;
    onCloseShare(): void;
    private _onOpenTag;
    private _onUiIntersectionChange;
    displayBubble(bubbleText: string): void;
    onCloseBubble(): void;
    private _onUserInitiatedDockDone;
    private _updateNumSaved;
    private _onLoadAddonImages;
    onSaveConfiguration(): Promise<{}>;
    private _onContenProblem;
    private _onBoundsUpdate;
    private _onDimensionsVisibilityChange;
    onPrintClicked(): void;
}
